### ISSUE TITLE
Add priority number for snippets

### ISSUE THREAD

**Issue by teppokoivula** [teppokoivula/Snippets#1]
Related to https://processwire.com/talk/topic/25814-snippets/?do=findComment&comment=216440, it would likely make sense to add priority number and/or drag'n'drop sorting for snippets. Saving this as a potential future enhancement.

**Comment by webmanufaktur** [comment]
Perfect addon within this module.

**Comment by teppokoivula** [comment]
This is now implemented in module version 1.1.0. Sort order can be defined in the data table view by dragging items.
