### ISSUE TITLE
PHP code support and/or Hanna Code integration

### ISSUE THREAD

**Issue by teppokoivula** [teppokoivula/Snippets#2]
At the moment this is just a rough idea, but perhaps integrating with Hanna Code would make sense? This would allow Snippets to remain simple and lightweight, while also supporting more advanced use cases.

**Comment by webmanufaktur** [comment]
Awesome addition!

**Comment by teppokoivula** [comment]
This is now implemented in 1.3.0. Note that Hanna Code support must be enabled first via Snippets module config screen; this opens quite a few new doors, so I think it's best to keep it as disabled by default option, at least for now.
