### ISSUE TITLE
MySQL error during installation

### ISSUE THREAD

**Issue by lesaff** [teppokoivula/Snippets#3]
When installing Snippets module on a local PW, once in a while I get this error:

Error message:
```
Aw shucks… Error: Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mysite.snippets' doesn't exist (in wire/core/WireDatabasePDO.php line 683)

#0 wire/core/WireDatabasePDO.php (683): PDO->query('SELECT apply_to...')
#1 site/modules/Snippets/Snippets.module.php(185): WireDatabasePDO->query('SELECT apply_to...')
#2 site/modules/Snippets/Snippets.module.php(48): Snippets->getSnippets()
#3 wire/core/Wire.php (417): Snippets->hookPageRender(Object(HookEvent))
#4 wire/core/WireHooks.php (1062): Wire->_callMethod('hookPageRender', Array)
#5 wire/core/Wire.php (485): WireHooks->runHooks(Object(Page), 'render', Array)
#6 /Volumes/SanDisk1
```

From modules.txt log
```
2021-08-24 05:51:37	admin	http://mysite.test/admin/module/	Module reported error during install (Snippets): SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'modified'
2021-08-24 05:51:37	admin	http://mysite.test/admin/module/	Installed module 'ProcessSnippets'
2021-08-24 05:51:37	admin	http://mysite.test/admin/module/	Installed module 'Snippets'
2021-08-24 05:51:37	admin	http://mysite.test/admin/module/	Saved module info caches
```

PW version: 3.0.183
PHP version: 7.4.22
MySQL version: 5.7.23
Laravel Valet version: 2.16.0

**Comment by teppokoivula** [comment]
Thanks for reporting this, @lesaff. So far I've been unable to reproduce this, but I've just pushed a new version that could fix the issue. Module needs to be reinstalled, though.

If you have a chance, please give the latest version a try and see if it works for you.

If it doesn't work, it'd be useful to see the output of following commands:

```
SELECT @@GLOBAL.sql_mode;
SELECT @@SESSION.sql_mode;
```

(This might have something to do with an SQL mode that differs from my setup.)

**Comment by lesaff** [comment]
Spot on @teppokoivula !

I uninstalled the previous version, check MySQL to make sure that `snippets` table has been removed.

Reinstalled the latest version (v1.03) and voila, it works.

Cheers

**Comment by lesaff** [comment]
Output for `SELECT @@GLOBAL.sql_mode;`

ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

For your additional info, in case you still need them.

Output for `SELECT @@SESSION.sql_mode;`

ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
