### ISSUE TITLE
Snippets don't get rendered if another is existing

### ISSUE THREAD

**Issue by webmanufaktur** [teppokoivula/Snippets#4]
It's me again... this time with a weird finding.

There are 2 snippets with schema.org markup and some {{page.variables}} within them.

The first one (schema-restaurant) should be placed before </head> for pages with a specific template.

The second one (schema-sitepage) should be placed at the same spot (before </head>) on all non-admin pages.

Expectation:
schema-restaurant would be rendered on all restaurant pages based on the template selector.
schema-sitepage would be rendered on all pages across that website which are accessible in the frontend for users/guests.

Reality:
schema-restaurant gets rendered on all restaurant pages based on the template selector.
schema-sitepage gets rendered only on restaurant pages based on the template selector from schema-restaurant.

What I tried:
I deleted all snippets, added them again one after another, changed the position of the snippets, tried different snippet names and yet the seconds snippet won't render on all non-admin pages. I have to disable the first one (schema-restaurant) in order to see my schema-sitepage snippet.

Related Screenshot can be found over in the support forum:

https://processwire.com/talk/topic/25814-snippets/?tab=comments#comment-216689

**Comment by teppokoivula** [comment]
Thanks for reporting this, @webmanufaktur. The issue was that after first non-match the module stopped processing any further snippets, instead of continuing to the next one. Should be fixed now in 1.0.4, though please let me know if it isn't :)

**Comment by webmanufaktur** [comment]
Thanks @teppokoivula. Did a small test run here and it seems that it's working fine now. Will do a real life test tomorrow and if there are any issues I'll report back.
