### ISSUE TITLE
Date formatting for system fields

### ISSUE THREAD

**Issue by webmanufaktur** [teppokoivula/Snippets#6]
While custom date fields can be set to display/output a date in a certain way, system fields don't have this option.

{{page.created}} and {{page.modified}} would always return timestamps.

This could be done either with custom PHP or Hanna Code as mentioned in #2 or maybe with something like _{{page.modified[Y-m-d]}}_. But that is just a thought right now.

**Comment by teppokoivula** [comment]
After considering this I think it's better to use an alternative route. Now that Hanna Code tags are supported in 1.3.0 that's one option, and if output is used within JavaScript, then formatting it on the front-end would be another one.

Primary technical issue here is that Snippets uses wirePopulateStringTags() behind the scenes, and there's no clean way to combine the two: wirePopulateStringTags and the WireTextTools class only detect tags containing valid characters, and while it would be possible to extend WireTextTools and replace the findPlaceholders method, I think that adds too much complexity.

Closing this issue, though let me know if there's something I've missed and I'd be glad to revisit it :)

**Comment by webmanufaktur** [comment]
The Hanna-solution works pretty well and gets me to where I want.
